version: '3.3'

services:

    mongo:
        image: mongo:4.2
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: passdb
        volumes:
            - 'mongo:/hauscv/data/db'

    mongo-express:
        image: mongo-express:latest
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: passdb

    telegram-bot:
        image: gcr.io/hauscv/bot:latest
        depends_on: 
            - 'mongo'
        restart: on-failure
        environment:
            TELEGRAM_TOKEN: 749483304:AAG1lFlA8w6i6aKiX7ePobHwn2pVD2eVxHk
            MONGO_URL: mongodb://admin:passdb@mongo:27017
        volumes:
            - './telegram-bot:/app'
        stdin_open: true
        tty: true

    surveillance:
        image: gcr.io/hauscv/surveillance:latest
        restart: on-failure
        environment:
            TELEGRAM_TOKEN: 749483304:AAG1lFlA8w6i6aKiX7ePobHwn2pVD2eVxHk
        volumes:
            - '.:/app'
        stdin_open: true
        tty: true
volumes:
    mongo:
    telegram-bot:
