FROM gcr.io/legos-247323/opencv/4.0.x:debian-buster-slim AS opencv

FROM gcr.io/legos-247323/googletest/1.8.x:debian-buster-slim AS gtest

FROM gcr.io/legos-247323/base:debian-buster-slim AS builder

MAINTAINER Jorge V. M. M. <jrgvmm@gmail.com>

# Copy lego's dependencies
COPY --from=opencv /opt/ /opt/
COPY --from=gtest /opt/ /opt/

# Install dev tools
RUN apt-get update \
	apt-get upgrade -y \
	&& apt-get install -y --no-install-recommends \
	build-essential \
	gdb \
	libssl-dev \
	libffi-dev \
	python-dev \
	python3-pip \
	vim \
	&& apt-get clean -y \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /
